// lib/main.dart
import 'package:flutter/material.dart';
import 'package:flutter_riverpod/flutter_riverpod.dart';
import 'package:firebase_core/firebase_core.dart';
import 'package:user_firestore/providers/user_provider.dart';
import 'package:user_firestore/repositories/user_repository.dart';
// Make sure to import your generated files and models
// import 'providers/user_provider.g.dart';
// import 'repositories/user_repository.g.dart';
import 'firebase_options.dart'; // Generated by FlutterFire CLI

void main() async {
  WidgetsFlutterBinding.ensureInitialized();
  await Firebase.initializeApp(options: DefaultFirebaseOptions.currentPlatform);
  runApp(ProviderScope(child: MyApp()));
}

class MyApp extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return MaterialApp(
      debugShowCheckedModeBanner: false,
      title: 'Firestore Riverpod CRUD',
      home: UserListScreen(),
    );
  }
}

// A ConsumerWidget is needed to interact with Riverpod
class UserListScreen extends ConsumerWidget {
  final TextEditingController _nameController = TextEditingController();

  @override
  Widget build(BuildContext context, WidgetRef ref) {
    // Watch the stream provider, which returns an AsyncValue
    final usersAsyncValue = ref.watch(usersStreamProvider);
    final userRepository = ref.watch(userRepositoryProvider);

    return Scaffold(
      appBar: AppBar(title: Text('Firestore Users')),
      body: usersAsyncValue.when(
        data: (users) {
          return ListView.builder(
            itemCount: users.length,
            itemBuilder: (context, index) {
              final user = users[index];
              return ListTile(
                title: Text(user.name),
                subtitle: Text('ID: ${user.id}'),
                trailing: IconButton(
                  icon: Icon(Icons.delete, color: Colors.red),
                  onPressed: () => userRepository.deleteUser(user.id),
                ),
                onTap: () =>
                    _editUserName(context, userRepository, user.id, user.name),
              );
            },
          );
        },
        loading: () => Center(child: CircularProgressIndicator()),
        error: (error, stack) => Center(child: Text('Error: $error')),
      ),
      floatingActionButton: FloatingActionButton(
        child: Icon(Icons.add),
        onPressed: () => _addUserName(context, userRepository),
      ),
    );
  }

  // Helper for CREATE operation (Add User)
  Future<void> _addUserName(BuildContext context, UserRepository repo) async {
    _nameController.clear();
    await showDialog(
      context: context,
      builder: (context) => AlertDialog(
        title: Text('Add User'),
        content: TextField(
          controller: _nameController,
          decoration: InputDecoration(hintText: 'Enter name'),
        ),
        actions: [
          TextButton(
            onPressed: () {
              if (_nameController.text.isNotEmpty) {
                repo.addUser(_nameController.text);
                Navigator.of(context).pop();
              }
            },
            child: Text('Add'),
          ),
        ],
      ),
    );
  }

  // Helper for UPDATE operation (Edit User Name)
  Future<void> _editUserName(
    BuildContext context,
    UserRepository repo,
    String id,
    String currentName,
  ) async {
    _nameController.text = currentName;
    await showDialog(
      context: context,
      builder: (context) => AlertDialog(
        title: Text('Edit User'),
        content: TextField(controller: _nameController),
        actions: [
          TextButton(
            onPressed: () {
              if (_nameController.text.isNotEmpty) {
                repo.updateUser(id, _nameController.text);
                Navigator.of(context).pop();
              }
            },
            child: Text('Save'),
          ),
        ],
      ),
    );
  }
}
